NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://api.domain.com/federation"
AUTH_SERVER="https://api.domain.com/auth"
TRANSFER_SERVER="https://api.domain.com"
SIGNING_KEY="GAE7N72TN77PQF3EGQAQZC4I2FWP5PYZULILTUXRQBHDDP5OLYGKWYMK"
HORIZON_URL="https://horizon.domain.com"
ACCOUNTS=[
"GAE7N72TN77PQF3EGQAQZC4I2FWP5PYZULILTUXRQBHDDP5OLYGKWYMK"
]
VERSION="2.0.0"
SQ02_EASTER_EGG="Log into series 2 of Stellar Quest then visit quest.stellar.org/series2. Finally drag and drop your Stellar Quest series 2 badge PNG images onto the screen. Enjoy!"


ORG_NAME="Organization Name"
ORG_DBA="Organization DBA"
ORG_URL="https://www.domain.com"
ORG_LOGO="https://www.domain.com/awesomelogo.png"
ORG_DESCRIPTION="Description of issuer"
ORG_PHYSICAL_ADDRESS="123 Sesame Street, New York, NY 12345, United States"
ORG_PHYSICAL_ADDRESS_ATTESTATION="https://www.domain.com/address_attestation.jpg"
ORG_PHONE_NUMBER="1 (123)-456-7890"
ORG_PHONE_NUMBER_ATTESTATION="https://www.domain.com/phone_attestation.jpg"
ORG_KEYBASE="accountname"
ORG_TWITTER="orgtweet"
ORG_GITHUB="orgcode"
ORG_OFFICIAL_EMAIL="support@domain.com"


name="Jane Jedidiah Johnson"
email="jane@domain.com"
keybase="crypto_jane"
twitter="crypto_jane"
github="crypto_jane"
id_photo_hash="be688838ca8686e5c90689bf2ab585cef1137c999b48c70b92f67a5c34dc15697b5d11c982ed6d71be1e1e7f7b4e0733884aa97c3f7a339a8ed03577cf74be09"
verification_photo_hash="016ba8c4cfde65af99cb5fa8b8a37e2eb73f481b3ae34991666df2e04feb6c038666ebd1ec2b6f623967756033c702dde5f423f7d47ab6ed1827ff53783731f7"


code="USD"
issuer="GAE7N72TN77PQF3EGQAQZC4I2FWP5PYZULILTUXRQBHDDP5OLYGKWYMK"
display_decimals=2


code="BTC"
issuer="GAE7N72TN77PQF3EGQAQZC4I2FWP5PYZULILTUXRQBHDDP5OLYGKWYMK"
display_decimals=7
anchor_asset_type="crypto"
anchor_asset="BTC"
redemption_instructions="Use SEP6 with our federation server"
collateral_addresses=["2C1mCx3ukix1KfegAY5zgQJV7sanAciZpv"]
collateral_address_signatures=["304502206e21798a42fae0e854281abd38bacd1aeed3ee3738d9e1446618c4571d10"]



code="GOAT"
issuer="GAE7N72TN77PQF3EGQAQZC4I2FWP5PYZULILTUXRQBHDDP5OLYGKWYMK"
display_decimals=2
name="goat share"
desc="1 GOAT token entitles you to a share of revenue from Elkins Goat Farm."
conditions="There will only ever be 10,000 GOAT tokens in existence. We will distribute the revenue share annually on Jan. 15th"
image="https://static.thenounproject.com/png/2292360-200.png"
fixed_number=10000// Let's show where the Internation Space Station currently is.
console.log("Let's see where the ISS is with Node " + process.version);


ALIAS="domain-us"
DISPLAY_NAME="Domain United States"
HOST="core-us.domain.com:11625"
PUBLIC_KEY="GCMGEBZIOFCUAVRM3XZ7XDLAJLBEPQHLZYLJ4CGY7CXP65BZF3MG3HCT"
HISTORY="http://history.domain.com/prd/core-live/core_live_003/"
